import type {
  ActivityLog,
  AnalyticsBreakdownItem,
  AnalyticsDoraMetric,
  AnalyticsDoraTrendPoint,
  AnalyticsExportRecord,
  AnalyticsFocusPoint,
  AnalyticsIssueAgingPoint,
  AnalyticsProjectSummary,
  AnalyticsProjectVelocityPoint,
  AnalyticsReport,
  AnalyticsRiskSummary,
  AnalyticsSchedule,
  AnalyticsSlaBreach,
  AnalyticsSprintProgress,
  AnalyticsStat,
  AnalyticsTeamLeaderboard,
  AnalyticsTeamWorkload,
  AnalyticsTrendPoint,
  AnalyticsTriagePoint,
  Comment,
  Issue,
  Notification,
  Project,
  Team,
  TeamInvite,
  TeamInviteDefaults,
  TeamMember,
  TeamPermission,
  TeamPolicy,
  TeamRole,
  TeamTrendPoint,
  User,
} from "@/types";

// ─── Users ────────────────────────────────────────────────────────────────────

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Alex Carter",
    email: "alex@devflow.io",
    imageUrl: "https://i.pravatar.cc/40?u=alex",
    role: "ADMIN",
    createdAt: "2025-01-10T08:00:00Z",
  },
  {
    id: "u2",
    name: "Priya Nair",
    email: "priya@devflow.io",
    imageUrl: "https://i.pravatar.cc/40?u=priya",
    role: "MANAGER",
    createdAt: "2025-01-12T09:00:00Z",
  },
  {
    id: "u3",
    name: "Jordan Lee",
    email: "jordan@devflow.io",
    imageUrl: "https://i.pravatar.cc/40?u=jordan",
    role: "DEVELOPER",
    createdAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "u4",
    name: "Sam Okafor",
    email: "sam@devflow.io",
    imageUrl: "https://i.pravatar.cc/40?u=sam",
    role: "DEVELOPER",
    createdAt: "2025-02-01T11:00:00Z",
  },
  {
    id: "u5",
    name: "Morgan Wu",
    email: "morgan@devflow.io",
    imageUrl: "https://i.pravatar.cc/40?u=morgan",
    role: "VIEWER",
    createdAt: "2025-02-10T12:00:00Z",
  },
];

export const currentUser = mockUsers[0];

// ─── Projects ─────────────────────────────────────────────────────────────────

export const mockProjects: Project[] = [
  {
    id: "p1",
    name: "E-Commerce Website",
    key: "ECOM",
    description:
      "Redesign and rebuild the main storefront with new checkout flow.",
    status: "ACTIVE",
    startDate: "2025-02-01T00:00:00Z",
    targetDate: "2025-06-30T00:00:00Z",
    createdAt: "2025-01-28T00:00:00Z",
    issueCount: 24,
    completedCount: 9,
    members: [mockUsers[0], mockUsers[1], mockUsers[2]],
  },
  {
    id: "p2",
    name: "DevFlow API",
    key: "DAPI",
    description: "Internal REST API powering the DevFlow platform.",
    status: "ACTIVE",
    startDate: "2025-03-01T00:00:00Z",
    targetDate: "2025-08-31T00:00:00Z",
    createdAt: "2025-02-25T00:00:00Z",
    issueCount: 18,
    completedCount: 11,
    members: [mockUsers[0], mockUsers[2], mockUsers[3]],
  },
  {
    id: "p3",
    name: "Mobile App",
    key: "MOB",
    description: "React Native app for iOS and Android.",
    status: "ON_HOLD",
    startDate: "2025-04-01T00:00:00Z",
    targetDate: "2025-12-31T00:00:00Z",
    createdAt: "2025-03-20T00:00:00Z",
    issueCount: 10,
    completedCount: 2,
    members: [mockUsers[1], mockUsers[3]],
  },
];

// ─── Issues ───────────────────────────────────────────────────────────────────

export const mockIssues: Issue[] = [
  {
    id: "i1",
    projectId: "p1",
    projectKey: "ECOM",
    issueKey: "ECOM-1",
    title: "Fix checkout page crash on mobile Safari",
    description:
      "The checkout page throws a JavaScript error on iOS Safari 16 when the user taps 'Place Order'. Stack trace attached.",
    type: "BUG",
    status: "IN_PROGRESS",
    priority: "CRITICAL",
    dueDate: "2025-05-20T00:00:00Z",
    assignee: mockUsers[2],
    reporter: mockUsers[1],
    labels: [{ id: "l1", name: "bug", color: "red" }],
    commentCount: 4,
    createdAt: "2025-05-01T10:00:00Z",
    updatedAt: "2025-05-15T14:00:00Z",
  },
  {
    id: "i2",
    projectId: "p1",
    projectKey: "ECOM",
    issueKey: "ECOM-2",
    title: "Add product image zoom feature",
    description:
      "Implement pinch-to-zoom and click-to-zoom for product images on the detail page.",
    type: "FEATURE",
    status: "TODO",
    priority: "MEDIUM",
    dueDate: "2025-06-15T00:00:00Z",
    assignee: mockUsers[3],
    reporter: mockUsers[0],
    labels: [{ id: "l2", name: "frontend", color: "blue" }],
    commentCount: 1,
    createdAt: "2025-05-05T09:00:00Z",
    updatedAt: "2025-05-05T09:00:00Z",
  },
  {
    id: "i3",
    projectId: "p2",
    projectKey: "DAPI",
    issueKey: "DAPI-1",
    title: "Implement rate limiting on /issues endpoint",
    description:
      "Add per-IP rate limiting (100 req/min) using Redis. Return 429 with Retry-After header.",
    type: "IMPROVEMENT",
    status: "IN_REVIEW",
    priority: "HIGH",
    dueDate: "2025-05-25T00:00:00Z",
    assignee: mockUsers[2],
    reporter: mockUsers[0],
    labels: [
      { id: "l3", name: "backend", color: "green" },
      { id: "l4", name: "security", color: "orange" },
    ],
    commentCount: 6,
    createdAt: "2025-05-08T11:00:00Z",
    updatedAt: "2025-05-18T16:00:00Z",
  },
  {
    id: "i4",
    projectId: "p2",
    projectKey: "DAPI",
    issueKey: "DAPI-2",
    title: "Write integration tests for auth routes",
    description:
      "Cover login, register, refresh token and logout endpoints with Jest + Supertest.",
    type: "TASK",
    status: "BACKLOG",
    priority: "LOW",
    assignee: mockUsers[3],
    reporter: mockUsers[1],
    labels: [{ id: "l5", name: "testing", color: "purple" }],
    commentCount: 0,
    createdAt: "2025-05-10T08:00:00Z",
    updatedAt: "2025-05-10T08:00:00Z",
  },
  {
    id: "i5",
    projectId: "p1",
    projectKey: "ECOM",
    issueKey: "ECOM-3",
    title: "Update product listing page design",
    type: "IMPROVEMENT",
    status: "DONE",
    priority: "MEDIUM",
    assignee: mockUsers[2],
    reporter: mockUsers[1],
    commentCount: 3,
    createdAt: "2025-04-20T10:00:00Z",
    updatedAt: "2025-05-12T09:00:00Z",
  },
  {
    id: "i6",
    projectId: "p3",
    projectKey: "MOB",
    issueKey: "MOB-1",
    title: "Set up React Native project structure",
    type: "TASK",
    status: "DONE",
    priority: "HIGH",
    assignee: mockUsers[3],
    reporter: mockUsers[0],
    commentCount: 2,
    createdAt: "2025-04-01T09:00:00Z",
    updatedAt: "2025-04-10T15:00:00Z",
  },
  {
    id: "i7",
    projectId: "p1",
    projectKey: "ECOM",
    issueKey: "ECOM-4",
    title: "Integrate Stripe payment gateway",
    type: "FEATURE",
    status: "BLOCKED",
    priority: "HIGH",
    dueDate: "2025-06-01T00:00:00Z",
    assignee: mockUsers[1],
    reporter: mockUsers[0],
    labels: [{ id: "l6", name: "payments", color: "yellow" }],
    commentCount: 8,
    createdAt: "2025-04-15T12:00:00Z",
    updatedAt: "2025-05-19T11:00:00Z",
  },
  {
    id: "i8",
    projectId: "p2",
    projectKey: "DAPI",
    issueKey: "DAPI-3",
    title: "Add pagination to /projects endpoint",
    description:
      "Implement cursor-based pagination with limit and cursor query params.",
    type: "IMPROVEMENT",
    status: "TODO",
    priority: "MEDIUM",
    dueDate: "2026-06-10T00:00:00Z",
    assignee: mockUsers[0],
    reporter: mockUsers[1],
    labels: [{ id: "l7", name: "backend", color: "green" }],
    commentCount: 2,
    createdAt: "2025-05-12T09:00:00Z",
    updatedAt: "2025-05-12T09:00:00Z",
  },
  {
    id: "i9",
    projectId: "p1",
    projectKey: "ECOM",
    issueKey: "ECOM-5",
    title: "Fix broken image URLs on product cards",
    description:
      "Product images return 404 in staging. Update CDN base URL in config.",
    type: "BUG",
    status: "IN_PROGRESS",
    priority: "HIGH",
    dueDate: "2026-05-30T00:00:00Z",
    assignee: mockUsers[4],
    reporter: mockUsers[0],
    labels: [
      { id: "l8", name: "frontend", color: "blue" },
      { id: "l9", name: "bug", color: "red" },
    ],
    commentCount: 3,
    createdAt: "2025-05-18T10:00:00Z",
    updatedAt: "2025-05-20T08:00:00Z",
  },
  {
    id: "i10",
    projectId: "p3",
    projectKey: "MOB",
    issueKey: "MOB-2",
    title: "Implement push notification support",
    description:
      "Integrate Firebase Cloud Messaging for iOS and Android push notifications.",
    type: "FEATURE",
    status: "BACKLOG",
    priority: "LOW",
    dueDate: "2026-09-01T00:00:00Z",
    assignee: mockUsers[3],
    reporter: mockUsers[1],
    labels: [{ id: "l10", name: "mobile", color: "purple" }],
    commentCount: 0,
    createdAt: "2025-05-20T14:00:00Z",
    updatedAt: "2025-05-20T14:00:00Z",
  },
];

// ─── Comments ─────────────────────────────────────────────────────────────────

export const mockComments: Comment[] = [
  {
    id: "c1",
    issueId: "i1",
    user: mockUsers[1],
    body: "Reproduced locally. The issue is with the async payment handler timing out.",
    createdAt: "2025-05-02T10:00:00Z",
    updatedAt: "2025-05-02T10:00:00Z",
  },
  {
    id: "c2",
    issueId: "i1",
    user: mockUsers[2],
    body: "I found the culprit — the promise was not being awaited in `handlePlaceOrder`. Fix is in PR #42.",
    createdAt: "2025-05-14T15:00:00Z",
    updatedAt: "2025-05-14T15:00:00Z",
  },
  {
    id: "c3",
    issueId: "i3",
    user: mockUsers[0],
    body: "Please also add the rate limit headers to the response so clients can self-regulate.",
    createdAt: "2025-05-10T09:00:00Z",
    updatedAt: "2025-05-10T09:00:00Z",
  },
];

// ─── Activity ─────────────────────────────────────────────────────────────────

export const mockActivity: ActivityLog[] = [
  {
    id: "a1",
    user: mockUsers[2],
    action: "changed status",
    details: "Status changed from TODO to IN_PROGRESS on ECOM-1",
    createdAt: "2025-05-15T14:00:00Z",
  },
  {
    id: "a2",
    user: mockUsers[1],
    action: "created issue",
    details: "Created DAPI-1: Implement rate limiting on /issues endpoint",
    createdAt: "2025-05-08T11:00:00Z",
  },
  {
    id: "a3",
    user: mockUsers[0],
    action: "assigned issue",
    details: "Assigned ECOM-4 to Priya Nair",
    createdAt: "2025-05-07T16:00:00Z",
  },
  {
    id: "a4",
    user: mockUsers[3],
    action: "closed issue",
    details: "Marked ECOM-3 as DONE",
    createdAt: "2025-05-12T09:00:00Z",
  },
  {
    id: "a5",
    user: mockUsers[2],
    action: "commented",
    details: "Commented on ECOM-1",
    createdAt: "2025-05-14T15:00:00Z",
  },
];

// ─── Notifications ────────────────────────────────────────────────────────────

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    title: "Issue Assigned",
    message: "Alex Carter assigned ECOM-4 to you",
    type: "assignment",
    createdAt: "2025-05-07T16:00:00Z",
  },
  {
    id: "n2",
    title: "Mentioned in Comment",
    message: "Jordan Lee mentioned you in ECOM-1",
    type: "mention",
    readAt: "2025-05-15T10:00:00Z",
    createdAt: "2025-05-14T15:00:00Z",
  },
  {
    id: "n3",
    title: "Status Changed",
    message: "DAPI-1 moved to IN_REVIEW",
    type: "status_change",
    createdAt: "2025-05-18T16:00:00Z",
  },
  {
    id: "n4",
    title: "Due Date Approaching",
    message: "ECOM-1 is due in 2 days",
    type: "due_date",
    createdAt: "2025-05-18T08:00:00Z",
  },
];

// ─── Dashboard Stats ──────────────────────────────────────────────────────────

export const dashboardStats = {
  totalIssues: 52,
  openIssues: 34,
  completedIssues: 18,
  overdueIssues: 5,
  totalProjects: 3,
  activeProjects: 2,
  teamMembers: 5,
};

export const weeklyTrend = [
  { week: "Apr 28", created: 8, resolved: 5 },
  { week: "May 5", created: 12, resolved: 7 },
  { week: "May 12", created: 6, resolved: 9 },
  { week: "May 19", created: 10, resolved: 8 },
  { week: "May 26", created: 7, resolved: 6 },
];

export const issuesByStatus = [
  { status: "Backlog", count: 8 },
  { status: "To Do", count: 12 },
  { status: "In Progress", count: 9 },
  { status: "In Review", count: 5 },
  { status: "Done", count: 18 },
];

export const issuesByPriority = [
  { priority: "Critical", count: 4 },
  { priority: "High", count: 11 },
  { priority: "Medium", count: 22 },
  { priority: "Low", count: 15 },
];

// ─── Analytics (Phase 2 mock data) ─────────────────────────────────────────

export const analyticsOverviewStats: AnalyticsStat[] = [
  {
    id: "total",
    label: "Total Issues",
    value: 134,
    change: 18,
    changeLabel: "vs last 30 days",
    iconKey: "totalIssues",
    iconBg: "bg-blue-50",
    iconColor: "text-blue-600",
  },
  {
    id: "completed",
    label: "Completed Issues",
    value: 42,
    change: 24,
    changeLabel: "vs last 30 days",
    iconKey: "completedIssues",
    iconBg: "bg-emerald-50",
    iconColor: "text-emerald-600",
  },
  {
    id: "progress",
    label: "In Progress",
    value: 27,
    change: -8,
    changeLabel: "vs last 30 days",
    iconKey: "inProgress",
    iconBg: "bg-amber-50",
    iconColor: "text-amber-600",
  },
  {
    id: "bugs",
    label: "Bug Issues",
    value: 23,
    change: -12,
    changeLabel: "vs last 30 days",
    iconKey: "bugIssues",
    iconBg: "bg-purple-50",
    iconColor: "text-purple-600",
  },
  {
    id: "members",
    label: "Active Members",
    value: 21,
    change: 5,
    changeLabel: "vs last 30 days",
    iconKey: "activeMembers",
    iconBg: "bg-teal-50",
    iconColor: "text-teal-600",
  },
];

export const analyticsProjectStats: AnalyticsStat[] = [
  {
    id: "active-projects",
    label: "Active Projects",
    value: 12,
    change: 10,
    changeLabel: "vs last 30 days",
    iconKey: "projects",
    iconBg: "bg-indigo-50",
    iconColor: "text-indigo-600",
  },
  {
    id: "velocity",
    label: "Avg Velocity",
    value: "48 pts",
    change: 6,
    changeLabel: "vs last 30 days",
    iconKey: "velocity",
    iconBg: "bg-blue-50",
    iconColor: "text-blue-600",
  },
  {
    id: "on-track",
    label: "On Track",
    value: 6,
    change: 12,
    changeLabel: "vs last 30 days",
    iconKey: "onTrack",
    iconBg: "bg-emerald-50",
    iconColor: "text-emerald-600",
  },
  {
    id: "at-risk",
    label: "At Risk",
    value: 3,
    change: -8,
    changeLabel: "vs last 30 days",
    iconKey: "atRisk",
    iconBg: "bg-amber-50",
    iconColor: "text-amber-600",
  },
];

export const analyticsIssueStats: AnalyticsStat[] = [
  {
    id: "total-issues",
    label: "Total Issues",
    value: 134,
    change: 14,
    changeLabel: "vs last 30 days",
    iconKey: "totalIssues",
    iconBg: "bg-blue-50",
    iconColor: "text-blue-600",
  },
  {
    id: "overdue",
    label: "Overdue",
    value: 12,
    change: -4,
    changeLabel: "vs last 30 days",
    iconKey: "overdue",
    iconBg: "bg-rose-50",
    iconColor: "text-rose-600",
  },
  {
    id: "cycle-time",
    label: "Avg Cycle Time",
    value: "4.6d",
    change: -6,
    changeLabel: "vs last 30 days",
    iconKey: "cycleTime",
    iconBg: "bg-violet-50",
    iconColor: "text-violet-600",
  },
  {
    id: "breaches",
    label: "SLA Breaches",
    value: 6,
    change: -2,
    changeLabel: "vs last 30 days",
    iconKey: "bugIssues",
    iconBg: "bg-orange-50",
    iconColor: "text-orange-600",
  },
];

export const analyticsTeamStats: AnalyticsStat[] = [
  {
    id: "members",
    label: "Active Members",
    value: 21,
    change: 5,
    changeLabel: "vs last 30 days",
    iconKey: "activeMembers",
    iconBg: "bg-teal-50",
    iconColor: "text-teal-600",
  },
  {
    id: "focus",
    label: "Focus Time",
    value: "30h",
    change: 8,
    changeLabel: "vs last 30 days",
    iconKey: "focus",
    iconBg: "bg-blue-50",
    iconColor: "text-blue-600",
  },
  {
    id: "throughput",
    label: "Throughput",
    value: "92 issues",
    change: 6,
    changeLabel: "vs last 30 days",
    iconKey: "throughput",
    iconBg: "bg-emerald-50",
    iconColor: "text-emerald-600",
  },
  {
    id: "cycle",
    label: "Avg Cycle Time",
    value: "4.2d",
    change: -5,
    changeLabel: "vs last 30 days",
    iconKey: "cycleTime",
    iconBg: "bg-violet-50",
    iconColor: "text-violet-600",
  },
];

export const analyticsDailyIssues: AnalyticsTrendPoint[] = [
  { label: "May 14", created: 22, closed: 16, resolved: 12 },
  { label: "May 15", created: 28, closed: 20, resolved: 14 },
  { label: "May 16", created: 26, closed: 18, resolved: 16 },
  { label: "May 17", created: 32, closed: 26, resolved: 18 },
  { label: "May 18", created: 24, closed: 24, resolved: 14 },
  { label: "May 19", created: 20, closed: 18, resolved: 10 },
  { label: "May 20", created: 26, closed: 20, resolved: 14 },
];

export const analyticsStatusBreakdown: AnalyticsBreakdownItem[] = [
  { name: "To Do", value: 34, color: "#3b82f6" },
  { name: "In Progress", value: 27, color: "#f59e0b" },
  { name: "In Review", value: 15, color: "#8b5cf6" },
  { name: "Done", value: 42, color: "#22c55e" },
  { name: "Blocked", value: 16, color: "#ef4444" },
];

export const analyticsPriorityBreakdown: AnalyticsBreakdownItem[] = [
  { name: "High", value: 48, color: "#ef4444" },
  { name: "Medium", value: 56, color: "#f59e0b" },
  { name: "Low", value: 20, color: "#22c55e" },
  { name: "Lowest", value: 10, color: "#9ca3af" },
];

export const analyticsProjects: AnalyticsProjectSummary[] = [
  {
    id: "p1",
    name: "E-commerce Website",
    key: "ECOM",
    icon: "🛍️",
    openIssues: 62,
    completed: 18,
    progress: 58,
    velocity: 14,
    health: "On Track",
    risk: "Low",
    barColor: "bg-emerald-500",
  },
  {
    id: "p2",
    name: "DevFlow API",
    key: "DAPI",
    icon: "</>",
    openIssues: 28,
    completed: 12,
    progress: 62,
    velocity: 11,
    health: "On Track",
    risk: "Low",
    barColor: "bg-emerald-500",
  },
  {
    id: "p3",
    name: "Mobile App",
    key: "MOB",
    icon: "📱",
    openIssues: 23,
    completed: 8,
    progress: 48,
    velocity: 7,
    health: "At Risk",
    risk: "Medium",
    barColor: "bg-amber-400",
  },
  {
    id: "p4",
    name: "Marketing Website",
    key: "MKT",
    icon: "🌐",
    openIssues: 14,
    completed: 5,
    progress: 35,
    velocity: 6,
    health: "At Risk",
    risk: "Medium",
    barColor: "bg-amber-400",
  },
  {
    id: "p5",
    name: "Internal Dashboard",
    key: "INT",
    icon: "🧭",
    openIssues: 7,
    completed: 3,
    progress: 30,
    velocity: 3,
    health: "Blocked",
    risk: "High",
    barColor: "bg-red-400",
  },
];

export const analyticsTeamWorkload: AnalyticsTeamWorkload[] = [
  {
    id: "tw1",
    name: "Karim Hossain",
    initials: "KH",
    color: "bg-sky-500",
    inProgress: 12,
    completed: 18,
  },
  {
    id: "tw2",
    name: "Rahim Ahmed",
    initials: "RA",
    color: "bg-emerald-500",
    inProgress: 9,
    completed: 14,
  },
  {
    id: "tw3",
    name: "Jannat Rahman",
    initials: "JR",
    color: "bg-pink-500",
    inProgress: 8,
    completed: 12,
  },
  {
    id: "tw4",
    name: "Sakib Al Hasan",
    initials: "SH",
    color: "bg-amber-500",
    inProgress: 6,
    completed: 10,
  },
  {
    id: "tw5",
    name: "Nusrat Jahan",
    initials: "NJ",
    color: "bg-orange-500",
    inProgress: 4,
    completed: 8,
  },
];

export const analyticsSprintProgress: AnalyticsSprintProgress = {
  sprint: "Sprint 2",
  dateRange: "May 10 - May 24",
  progress: 62,
  completed: "31 / 50 issues",
  daysLeft: "4 days",
  status: "Active",
};

export const analyticsProjectVelocity: AnalyticsProjectVelocityPoint[] = [
  { sprint: "Sprint 8", completed: 40, scope: 32 },
  { sprint: "Sprint 9", completed: 48, scope: 45 },
  { sprint: "Sprint 10", completed: 45, scope: 38 },
  { sprint: "Sprint 11", completed: 55, scope: 52 },
  { sprint: "Sprint 12", completed: 50, scope: 47 },
];

export const analyticsProjectRiskSummary: AnalyticsRiskSummary[] = [
  { label: "On Track", value: 3, color: "text-emerald-600" },
  { label: "At Risk", value: 2, color: "text-amber-600" },
  { label: "Blocked", value: 1, color: "text-red-600" },
];

export const analyticsIssueAging: AnalyticsIssueAgingPoint[] = [
  { bucket: "0-2 days", count: 28 },
  { bucket: "3-7 days", count: 46 },
  { bucket: "8-14 days", count: 33 },
  { bucket: "15+ days", count: 27 },
];

export const analyticsIssueTriage: AnalyticsTriagePoint[] = [
  { week: "Apr 22", triaged: 32, created: 28 },
  { week: "Apr 29", triaged: 40, created: 34 },
  { week: "May 6", triaged: 36, created: 30 },
  { week: "May 13", triaged: 44, created: 38 },
  { week: "May 20", triaged: 41, created: 35 },
];

export const analyticsSlaSummary = {
  breached: 6,
  atRisk: 14,
  withinSla: 92,
};

export const analyticsSlaBreaches: AnalyticsSlaBreach[] = [
  {
    id: "sla1",
    issueKey: "ECOM-97",
    title: "Checkout regression in Safari",
    priority: "HIGH",
    daysOver: 3,
  },
  {
    id: "sla2",
    issueKey: "DAPI-42",
    title: "Rate limit missing on search",
    priority: "MEDIUM",
    daysOver: 2,
  },
  {
    id: "sla3",
    issueKey: "MOB-18",
    title: "Push notification queue stuck",
    priority: "CRITICAL",
    daysOver: 5,
  },
];

export const analyticsTeamLeaderboard: AnalyticsTeamLeaderboard[] = [
  {
    id: "tl1",
    name: "Karim Hossain",
    role: "Developer",
    completed: 32,
    quality: 94,
    trend: 6,
  },
  {
    id: "tl2",
    name: "Nusrat Jahan",
    role: "Designer",
    completed: 24,
    quality: 91,
    trend: 4,
  },
  {
    id: "tl3",
    name: "Rahim Ahmed",
    role: "Developer",
    completed: 28,
    quality: 89,
    trend: -2,
  },
  {
    id: "tl4",
    name: "Jannat Rahman",
    role: "QA Engineer",
    completed: 21,
    quality: 92,
    trend: 3,
  },
  {
    id: "tl5",
    name: "Sakib Al Hasan",
    role: "Developer",
    completed: 19,
    quality: 87,
    trend: 1,
  },
];

export const analyticsTeamFocusTrend: AnalyticsFocusPoint[] = [
  { week: "Apr 22", focusHours: 26, meetingHours: 10 },
  { week: "Apr 29", focusHours: 28, meetingHours: 9 },
  { week: "May 6", focusHours: 30, meetingHours: 8 },
  { week: "May 13", focusHours: 27, meetingHours: 11 },
  { week: "May 20", focusHours: 31, meetingHours: 7 },
];

export const analyticsReportLibrary: AnalyticsReport[] = [
  {
    id: "r1",
    title: "Sprint Health Overview",
    description: "Velocity, scope, and blockers across active sprints.",
    category: "Delivery",
    lastRun: "2 hours ago",
    owner: "Munna Islam",
    format: "PDF",
  },
  {
    id: "r2",
    title: "Weekly Issue Summary",
    description: "Creation, resolution, and aging metrics by team.",
    category: "Issues",
    lastRun: "Yesterday",
    owner: "Nusrat Jahan",
    format: "CSV",
  },
  {
    id: "r3",
    title: "Release Readiness",
    description: "Open risks, QA status, and change failure rate.",
    category: "Quality",
    lastRun: "3 days ago",
    owner: "Karim Hossain",
    format: "PDF",
  },
  {
    id: "r4",
    title: "Team Capacity Plan",
    description: "Focus time, load, and staffing projections.",
    category: "Team",
    lastRun: "May 18",
    owner: "Jannat Rahman",
    format: "XLSX",
  },
];

export const analyticsReportExports: AnalyticsExportRecord[] = [
  {
    id: "e1",
    name: "Sprint Health Overview",
    format: "PDF",
    size: "1.4 MB",
    createdAt: "May 20, 10:12 AM",
    status: "Complete",
  },
  {
    id: "e2",
    name: "Weekly Issue Summary",
    format: "CSV",
    size: "840 KB",
    createdAt: "May 19, 05:30 PM",
    status: "Complete",
  },
  {
    id: "e3",
    name: "Release Readiness",
    format: "PDF",
    size: "1.1 MB",
    createdAt: "May 18, 09:45 AM",
    status: "Failed",
  },
  {
    id: "e4",
    name: "Team Capacity Plan",
    format: "XLSX",
    size: "640 KB",
    createdAt: "May 17, 04:18 PM",
    status: "Complete",
  },
];

export const analyticsReportSchedules: AnalyticsSchedule[] = [
  {
    id: "s1",
    name: "Monday Sprint Digest",
    frequency: "Weekly",
    nextRun: "May 27, 09:00 AM",
    recipients: 12,
  },
  {
    id: "s2",
    name: "Issue Aging Alert",
    frequency: "Daily",
    nextRun: "May 22, 08:00 AM",
    recipients: 6,
  },
  {
    id: "s3",
    name: "Release Health Snapshot",
    frequency: "Bi-weekly",
    nextRun: "Jun 1, 11:30 AM",
    recipients: 9,
  },
];

export const analyticsDoraMetrics: AnalyticsDoraMetric[] = [
  {
    id: "d1",
    label: "Deployment Frequency",
    value: "5.2",
    change: 12,
    target: "6 per week",
    status: "Warn",
  },
  {
    id: "d2",
    label: "Lead Time for Changes",
    value: "2.1",
    change: -9,
    target: "< 2 days",
    status: "Warn",
  },
  {
    id: "d3",
    label: "Change Failure Rate",
    value: "7.4%",
    change: -3,
    target: "< 10%",
    status: "Good",
  },
  {
    id: "d4",
    label: "MTTR",
    value: "3.6",
    change: -11,
    target: "< 4 hours",
    status: "Good",
  },
];

export const analyticsDoraTrend: AnalyticsDoraTrendPoint[] = [
  { month: "Jan", deploys: 18, leadTime: 2.8, failureRate: 9.4, mttr: 4.6 },
  { month: "Feb", deploys: 20, leadTime: 2.6, failureRate: 8.6, mttr: 4.2 },
  { month: "Mar", deploys: 22, leadTime: 2.4, failureRate: 7.8, mttr: 3.9 },
  { month: "Apr", deploys: 24, leadTime: 2.3, failureRate: 7.6, mttr: 3.7 },
  { month: "May", deploys: 26, leadTime: 2.1, failureRate: 7.4, mttr: 3.6 },
];

// ─── Team (Phase 1-3 mock data) ─────────────────────────────────────────────

export const mockTeamMembers: TeamMember[] = [
  {
    id: "tm1",
    name: "Munna Islam",
    email: "munna.islam@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=munna",
    role: "Admin",
    team: "Product",
    status: "Active",
    joinedAt: "2024-04-10",
    isCurrentUser: true,
  },
  {
    id: "tm2",
    name: "Nusrat Jahan",
    email: "nusrat.jahan@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=nusrat",
    role: "Developer",
    team: "Development",
    status: "Active",
    joinedAt: "2024-04-12",
  },
  {
    id: "tm3",
    name: "Rahim Ahmed",
    email: "rahim.ahmed@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=rahim",
    role: "Developer",
    team: "Development",
    status: "Active",
    joinedAt: "2024-04-15",
  },
  {
    id: "tm4",
    name: "Sakib Al Hasan",
    email: "sakib.hasan@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=sakib",
    role: "QA Engineer",
    team: "Quality Assurance",
    status: "Active",
    joinedAt: "2024-04-18",
  },
  {
    id: "tm5",
    name: "Jannat Rahman",
    email: "jannat.rahman@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=jannat",
    role: "Designer",
    team: "Design",
    status: "Active",
    joinedAt: "2024-04-20",
  },
  {
    id: "tm6",
    name: "Karim Hossain",
    email: "karim.hossain@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=karim",
    role: "Product Manager",
    team: "Product",
    status: "Active",
    joinedAt: "2024-04-10",
  },
  {
    id: "tm7",
    name: "Tanvir Ahmed",
    email: "tanvir.ahmed@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=tanvir",
    role: "Developer",
    team: "Development",
    status: "Active",
    joinedAt: "2024-04-25",
  },
  {
    id: "tm8",
    name: "Faria Islam",
    email: "faria.islam@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=faria",
    role: "QA Engineer",
    team: "Quality Assurance",
    status: "Away",
    joinedAt: "2024-04-28",
  },
  {
    id: "tm9",
    name: "Mehedi Hasan",
    email: "mehedi.hasan@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=mehedi",
    role: "DevOps Engineer",
    team: "DevOps",
    status: "Inactive",
    joinedAt: "2024-05-02",
  },
  {
    id: "tm10",
    name: "Sara Akter",
    email: "sara.akter@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=sara",
    role: "Developer",
    team: "Development",
    status: "Inactive",
    joinedAt: "2024-05-05",
  },
  {
    id: "tm11",
    name: "Arif Hossain",
    email: "arif.hossain@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=arif",
    role: "Developer",
    team: "Development",
    status: "Active",
    joinedAt: "2024-04-08",
  },
  {
    id: "tm12",
    name: "Tashina Akter",
    email: "tashina.akter@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=tashina",
    role: "QA Engineer",
    team: "Quality Assurance",
    status: "Active",
    joinedAt: "2024-04-22",
  },
  {
    id: "tm13",
    name: "Rayhan Kabir",
    email: "rayhan.kabir@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=rayhan",
    role: "Developer",
    team: "Development",
    status: "Active",
    joinedAt: "2024-04-29",
  },
  {
    id: "tm14",
    name: "Farhan Ahmed",
    email: "farhan.ahmed@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=farhan",
    role: "Developer",
    team: "Development",
    status: "Active",
    joinedAt: "2024-04-16",
  },
  {
    id: "tm15",
    name: "Nabila Noor",
    email: "nabila.noor@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=nabila",
    role: "Designer",
    team: "Design",
    status: "Active",
    joinedAt: "2024-04-14",
  },
  {
    id: "tm16",
    name: "Sabbir Rahman",
    email: "sabbir.rahman@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=sabbir",
    role: "DevOps Engineer",
    team: "DevOps",
    status: "Active",
    joinedAt: "2024-04-11",
  },
  {
    id: "tm17",
    name: "Israt Jahan",
    email: "israt.jahan@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=israt",
    role: "QA Engineer",
    team: "Quality Assurance",
    status: "Active",
    joinedAt: "2024-04-19",
  },
  {
    id: "tm18",
    name: "Ahsan Habib",
    email: "ahsan.habib@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=ahsan",
    role: "Support Engineer",
    team: "Support",
    status: "Active",
    joinedAt: "2024-04-24",
  },
  {
    id: "tm19",
    name: "Mila Islam",
    email: "mila.islam@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=mila",
    role: "Developer",
    team: "Development",
    status: "Active",
    joinedAt: "2024-04-26",
  },
  {
    id: "tm20",
    name: "Sohan Ahmed",
    email: "sohan.ahmed@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=sohan",
    role: "Developer",
    team: "Development",
    status: "Active",
    joinedAt: "2024-04-27",
  },
  {
    id: "tm21",
    name: "Raisa Khan",
    email: "raisa.khan@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=raisa",
    role: "Product Manager",
    team: "Product",
    status: "Active",
    joinedAt: "2024-04-13",
  },
  {
    id: "tm22",
    name: "Alif Hasan",
    email: "alif.hasan@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=alif",
    role: "QA Engineer",
    team: "Quality Assurance",
    status: "Active",
    joinedAt: "2024-04-21",
  },
  {
    id: "tm23",
    name: "Ridoy Karim",
    email: "ridoy.karim@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=ridoy",
    role: "Support Engineer",
    team: "Support",
    status: "Active",
    joinedAt: "2024-04-30",
  },
  {
    id: "tm24",
    name: "Nayeem Hasan",
    email: "nayeem.hasan@example.com",
    avatarUrl: "https://i.pravatar.cc/40?u=nayeem",
    role: "Admin",
    team: "Platform",
    status: "Active",
    joinedAt: "2024-04-09",
  },
];

export const mockTeamInvites: TeamInvite[] = [
  {
    id: "ti1",
    email: "arif.hossain@example.com",
    role: "Developer",
    invitedAt: "2024-05-04",
  },
  {
    id: "ti2",
    email: "tashina.akter@example.com",
    role: "QA Engineer",
    invitedAt: "2024-05-03",
  },
  {
    id: "ti3",
    email: "rayhan.kabir@example.com",
    role: "Developer",
    invitedAt: "2024-05-02",
  },
];

export const mockTeamRoles: TeamRole[] = [
  {
    id: "admin",
    name: "Admin",
    description: "Full access to settings, billing, and roles.",
    memberCount: 2,
    badgeClass: "bg-blue-100 text-blue-700",
    chartColor: "#2563eb",
  },
  {
    id: "developer",
    name: "Developer",
    description: "Build features, triage issues, and ship releases.",
    memberCount: 9,
    badgeClass: "bg-indigo-100 text-indigo-700",
    chartColor: "#6366f1",
  },
  {
    id: "qa",
    name: "QA Engineer",
    description: "Own test plans, bug triage, and release checks.",
    memberCount: 5,
    badgeClass: "bg-emerald-100 text-emerald-700",
    chartColor: "#10b981",
  },
  {
    id: "designer",
    name: "Designer",
    description: "Design flows, prototypes, and usability reviews.",
    memberCount: 2,
    badgeClass: "bg-pink-100 text-pink-700",
    chartColor: "#ec4899",
  },
  {
    id: "product",
    name: "Product Manager",
    description: "Define roadmap, scope, and feature requirements.",
    memberCount: 2,
    badgeClass: "bg-amber-100 text-amber-700",
    chartColor: "#f59e0b",
  },
  {
    id: "devops",
    name: "DevOps Engineer",
    description: "Run infrastructure, deployments, and observability.",
    memberCount: 2,
    badgeClass: "bg-slate-100 text-slate-700",
    chartColor: "#64748b",
  },
  {
    id: "support",
    name: "Support Engineer",
    description: "Handle customer tickets and incident follow-ups.",
    memberCount: 2,
    badgeClass: "bg-rose-100 text-rose-700",
    chartColor: "#f43f5e",
  },
];

export const mockTeamPermissions: TeamPermission[] = [
  {
    id: "tp1",
    action: "Invite members",
    description: "Send team invites and manage pending requests.",
    access: {
      admin: true,
      developer: false,
      qa: false,
      designer: false,
      product: true,
      devops: false,
      support: false,
    },
  },
  {
    id: "tp2",
    action: "Manage roles",
    description: "Edit role permissions and access levels.",
    access: {
      admin: true,
      developer: false,
      qa: false,
      designer: false,
      product: true,
      devops: false,
      support: false,
    },
  },
  {
    id: "tp3",
    action: "Edit issues",
    description: "Create, edit, and assign issues.",
    access: {
      admin: true,
      developer: true,
      qa: true,
      designer: true,
      product: true,
      devops: true,
      support: true,
    },
  },
  {
    id: "tp4",
    action: "Delete projects",
    description: "Archive or permanently delete projects.",
    access: {
      admin: true,
      developer: false,
      qa: false,
      designer: false,
      product: false,
      devops: false,
      support: false,
    },
  },
  {
    id: "tp5",
    action: "View analytics",
    description: "Access team analytics and reports.",
    access: {
      admin: true,
      developer: true,
      qa: true,
      designer: false,
      product: true,
      devops: true,
      support: false,
    },
  },
  {
    id: "tp6",
    action: "Manage billing",
    description: "Update subscription and payment methods.",
    access: {
      admin: true,
      developer: false,
      qa: false,
      designer: false,
      product: false,
      devops: false,
      support: false,
    },
  },
];

export const mockTeams: Team[] = [
  {
    id: "team1",
    name: "Product",
    description: "Owns roadmap, prioritization, and stakeholder alignment.",
    lead: {
      name: "Munna Islam",
      role: "Admin",
      avatarUrl: "https://i.pravatar.cc/40?u=munna",
    },
    memberCount: 6,
    projectCount: 4,
    timezone: "GMT +6",
    members: [
      { name: "Munna Islam", avatarUrl: "https://i.pravatar.cc/40?u=munna" },
      { name: "Karim Hossain", avatarUrl: "https://i.pravatar.cc/40?u=karim" },
      { name: "Raisa Khan", avatarUrl: "https://i.pravatar.cc/40?u=raisa" },
    ],
  },
  {
    id: "team2",
    name: "Development",
    description: "Builds product features and core platform services.",
    lead: {
      name: "Nusrat Jahan",
      role: "Developer",
      avatarUrl: "https://i.pravatar.cc/40?u=nusrat",
    },
    memberCount: 9,
    projectCount: 6,
    timezone: "GMT +6",
    members: [
      { name: "Nusrat Jahan", avatarUrl: "https://i.pravatar.cc/40?u=nusrat" },
      { name: "Rahim Ahmed", avatarUrl: "https://i.pravatar.cc/40?u=rahim" },
      { name: "Tanvir Ahmed", avatarUrl: "https://i.pravatar.cc/40?u=tanvir" },
    ],
  },
  {
    id: "team3",
    name: "Quality Assurance",
    description: "Owns testing, quality checks, and regression coverage.",
    lead: {
      name: "Sakib Al Hasan",
      role: "QA Engineer",
      avatarUrl: "https://i.pravatar.cc/40?u=sakib",
    },
    memberCount: 4,
    projectCount: 3,
    timezone: "GMT +6",
    members: [
      { name: "Sakib Al Hasan", avatarUrl: "https://i.pravatar.cc/40?u=sakib" },
      { name: "Faria Islam", avatarUrl: "https://i.pravatar.cc/40?u=faria" },
      {
        name: "Tashina Akter",
        avatarUrl: "https://i.pravatar.cc/40?u=tashina",
      },
    ],
  },
  {
    id: "team4",
    name: "Design",
    description: "Designs user flows, UI systems, and brand assets.",
    lead: {
      name: "Jannat Rahman",
      role: "Designer",
      avatarUrl: "https://i.pravatar.cc/40?u=jannat",
    },
    memberCount: 2,
    projectCount: 2,
    timezone: "GMT +6",
    members: [
      { name: "Jannat Rahman", avatarUrl: "https://i.pravatar.cc/40?u=jannat" },
      { name: "Nabila Noor", avatarUrl: "https://i.pravatar.cc/40?u=nabila" },
    ],
  },
  {
    id: "team5",
    name: "DevOps",
    description: "Runs infrastructure, pipelines, and incident response.",
    lead: {
      name: "Sabbir Rahman",
      role: "DevOps Engineer",
      avatarUrl: "https://i.pravatar.cc/40?u=sabbir",
    },
    memberCount: 2,
    projectCount: 2,
    timezone: "GMT +6",
    members: [
      { name: "Sabbir Rahman", avatarUrl: "https://i.pravatar.cc/40?u=sabbir" },
      { name: "Mehedi Hasan", avatarUrl: "https://i.pravatar.cc/40?u=mehedi" },
    ],
  },
  {
    id: "team6",
    name: "Support",
    description: "Handles customer tickets and escalations.",
    lead: {
      name: "Ahsan Habib",
      role: "Support Engineer",
      avatarUrl: "https://i.pravatar.cc/40?u=ahsan",
    },
    memberCount: 3,
    projectCount: 1,
    timezone: "GMT +6",
    members: [
      { name: "Ahsan Habib", avatarUrl: "https://i.pravatar.cc/40?u=ahsan" },
      { name: "Ridoy Karim", avatarUrl: "https://i.pravatar.cc/40?u=ridoy" },
      { name: "Arif Hossain", avatarUrl: "https://i.pravatar.cc/40?u=arif" },
    ],
  },
];

export const mockTeamTrends: TeamTrendPoint[] = [
  { date: "Apr 8", members: 14 },
  { date: "Apr 15", members: 16 },
  { date: "Apr 22", members: 18 },
  { date: "Apr 29", members: 20 },
  { date: "May 6", members: 24 },
];

export const mockTeamPolicies: TeamPolicy[] = [
  {
    id: "pol1",
    label: "Require approval for new members",
    description: "New invites must be approved by an admin.",
    enabled: true,
  },
  {
    id: "pol2",
    label: "Allow external collaborator access",
    description: "Invite partners with limited project access.",
    enabled: false,
  },
  {
    id: "pol3",
    label: "Enable audit logging",
    description: "Track role changes and member activity.",
    enabled: true,
  },
  {
    id: "pol4",
    label: "Weekly access review reminders",
    description: "Notify admins to review access every week.",
    enabled: true,
  },
];

export const mockTeamInviteDefaults: TeamInviteDefaults = {
  defaultRole: "Developer",
  expiryDays: 7,
  requireTwoFactor: true,
  allowGuestAccess: false,
};

// ─── Settings ─────────────────────────────────────────────────────────────────

import type {
  ActiveSession,
  AutomationRule,
  CustomField,
  Integration,
  Invoice,
} from "@/types";

export const mockCustomFields: CustomField[] = [
  {
    id: "cf1",
    name: "Story Points",
    type: "number",
    required: false,
    applicableTo: "issue",
  },
  {
    id: "cf2",
    name: "Sprint",
    type: "text",
    required: false,
    applicableTo: "issue",
  },
  {
    id: "cf3",
    name: "Release Date",
    type: "date",
    required: false,
    applicableTo: "project",
  },
  {
    id: "cf4",
    name: "Environment",
    type: "select",
    required: true,
    applicableTo: "issue",
  },
  {
    id: "cf5",
    name: "Client Name",
    type: "text",
    required: false,
    applicableTo: "project",
  },
];

export const mockAutomationRules: AutomationRule[] = [
  {
    id: "ar1",
    name: "Auto-assign on create",
    trigger: "Issue created",
    action: "Assign to project lead",
    enabled: true,
  },
  {
    id: "ar2",
    name: "Close on merge",
    trigger: "PR merged",
    action: "Set issue status to Done",
    enabled: true,
  },
  {
    id: "ar3",
    name: "Overdue alert",
    trigger: "Due date passed",
    action: "Send notification to assignee",
    enabled: false,
  },
  {
    id: "ar4",
    name: "Move to In Review",
    trigger: "PR opened",
    action: "Set issue status to In Review",
    enabled: true,
  },
];

export const mockIntegrations: Integration[] = [
  {
    id: "int1",
    name: "GitHub",
    icon: "github",
    connected: true,
    connectedAt: "2024-03-10",
    description: "Sync issues with GitHub repositories.",
  },
  {
    id: "int2",
    name: "Slack",
    icon: "slack",
    connected: true,
    connectedAt: "2024-04-01",
    description: "Get notifications in Slack channels.",
  },
  {
    id: "int3",
    name: "Jira",
    icon: "jira",
    connected: false,
    description: "Import and sync issues from Jira.",
  },
  {
    id: "int4",
    name: "Figma",
    icon: "figma",
    connected: false,
    description: "Attach Figma designs to issues.",
  },
  {
    id: "int5",
    name: "Notion",
    icon: "notion",
    connected: false,
    description: "Link Notion docs to projects.",
  },
  {
    id: "int6",
    name: "Google Drive",
    icon: "google",
    connected: true,
    connectedAt: "2024-05-15",
    description: "Attach files from Google Drive.",
  },
];

export const mockActiveSessions: ActiveSession[] = [
  {
    id: "ses1",
    device: "MacBook Pro",
    browser: "Chrome 124",
    location: "Dhaka, BD",
    lastSeen: "Just now",
    isCurrent: true,
  },
  {
    id: "ses2",
    device: "iPhone 15",
    browser: "Safari 17",
    location: "Dhaka, BD",
    lastSeen: "2 hours ago",
    isCurrent: false,
  },
  {
    id: "ses3",
    device: "Windows PC",
    browser: "Edge 123",
    location: "Dhaka, BD",
    lastSeen: "Yesterday",
    isCurrent: false,
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: "inv1",
    date: "May 1, 2026",
    amount: "$29.00",
    plan: "Pro",
    status: "paid",
  },
  {
    id: "inv2",
    date: "Apr 1, 2026",
    amount: "$29.00",
    plan: "Pro",
    status: "paid",
  },
  {
    id: "inv3",
    date: "Mar 1, 2026",
    amount: "$29.00",
    plan: "Pro",
    status: "paid",
  },
  {
    id: "inv4",
    date: "Feb 1, 2026",
    amount: "$29.00",
    plan: "Pro",
    status: "paid",
  },
  {
    id: "inv5",
    date: "Jan 1, 2026",
    amount: "$29.00",
    plan: "Pro",
    status: "paid",
  },
];
